name: build
on: [push]


jobs:
  Main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:        
          modules: 'core gui widgets'
          
      - name: Compile With CMake   
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.4.1     
      
      - name: install CMake  
        uses: lukka/get-cmake@latest          
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:        
          modules: 'core gui widgets'

      - name: Install Curl 
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install curl

      - name: Compile With CMake   
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          cmake --build . --config Release --target upload_file
          
          
# Upload Result
#    - name: upload executable
#      uses: actions/upload-artifact@v2
#      with:
#        name: ${{matrix.os}}
#        path: |
#          ouputnamefile